version: "3.8"
services:
  atask:
    image: atask
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "25"
    volumes:
       - ./usr/src/atask
    ports:
      - 3000:3000
    restart: unless-stopped
    container_name: atask