export const userConstants = {
  SEARCH_USER_REQUEST: "SEARCH_USER_REQUEST",
  SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE",
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  USER_REPOSITORY_REQUEST: "USER_REPOSITORY_REQUEST",
  USER_REPOSITORY_FAILURE: "USER_REPOSITORY_FAILURE",
  USER_REPOSITORY_SUCCESS: "USER_REPOSITORY_SUCCESS"
}
